### PR TITLE
Change the compiler's error strings from orange to red

### LINKED ISSUE #112: Type errors are displaying in orange color when should it be red
## Environment/Browser
Chrome

## Description
Type errors are displaying in orange color when should it be red

## Steps to reproduce
1. 
```js
pragma solidity ^0.4.21;

contract HelloWorld {
    string public message;
    
    asdf
}
```
2. Compile the Smart Contract

## Expected result
The error messages are displayed in red color

## Actual result
The message is displayed in orange, giving the impression that it was a simple warning. 

## Reproducible
100%

### PR DESCRIPTION
**Pull request by waheed25**
this closes #112

### CODE REVIEW

File: src/components/projecteditor/compiler.js [hunk 1]
```diff
@@ -164,7 +164,13 @@ export default class Compiler extends Component {
                     }
                     else {
                         (data.errors || []).map((row)=>{
-                            this.consoleRows.push({channel:3,msg:row.formattedMessage});
+                            if(row.severity==="warning")
```
Comment (javier-tarazaga) [inline src/components/projecteditor/compiler.js]: Please follow same this code conventions for now: 

```js

if (row.severity === "warning") {
...
} else {
...
}
```

Also the same as the this.consoleRows.push code (I would use the same format as the one in the else clause)

Comment (javier-tarazaga) [reply src/components/projecteditor/compiler.js]: Also, do we have any other level apart from "warning" and "error"  which would be interesting to distinguish? This way whatever is not a warning will be perceived as an error.

Comment (filippsen) [reply src/components/projecteditor/compiler.js]: @javier-tarazaga No. At the moment, `severity` is set to either `warning` or `error`.
Reference: https://github.com/ethereum/solidity/blob/develop/libsolidity/interface/StandardCompiler.cpp#L50

You could differentiate between the different error types (`Type` enum, mentioned in previous comment) by reading the `type` field, but I don't see the point in this case.
